### ISSUE TITLE
Thanks but need some help

### ISSUE THREAD

**Issue by lechyyy** [Its-Vichy/CometCNC#1]
Hey vichy, what am I supposed to put in this field?
![image](https://user-images.githubusercontent.com/105937945/169570990-6ccf01df-0b4e-4239-b09f-6d1e208e72ae.png)

**Comment by lechyyy** [comment]
the stresser api?

**Comment by lechyyy** [comment]
Which files am I supposed to use to host the api?

**Comment by Its-Vichy** [comment]
This function was used to add api on the cnc, not to host an api.

**Comment by lechyyy** [comment]
So I can just leave it like that, right?

**Comment by Its-Vichy** [comment]
yes

**Comment by lechyyy** [comment]
Thanks, do you have a discord token generator with an ai solver that works? if so, can you release it?
